### PR TITLE
Move python code to pythonx dir

### PR DESCRIPTION
**Pull request by lucc**
That's where it belongs. See `:h pythonx-directory`.

### CODE REVIEW

**Comment by BlackIkeEagle** [comment]
I'd love to merge this, but I'm a bit afraid of the failing integration tests

**Comment by lucc** [comment]
Will check later

**Comment by BlackIkeEagle** [comment]
thanks alot

**Comment by lucc** [comment]
I removed the commit that removes the python startup file and now the test on travis fails only as bad as it does on v2-integration.

I am not sure why my plan to remove it doesn't work.

**Comment by lucc** [comment]
Maybe we can mark that one test as a known failure (even though *I* don't understand why it fails).

**Comment by BlackIkeEagle** [comment]
@lucc that is already great, I've currently accepted it as failing for unknown reason.

**Pull request merged**
