### PR TITLE
Fix some problems with the test runs on travis

### LINKED ISSUE #284: Trouble with the ruby test suite
I am experiencing quite some trouble with the ruby test suite and also see random test failures on travis. I must admit that I have no experience with ruby, rake, bundler, gem or rspec yet so maybe I am missing something obvious here (but I assume that can only be the case for my local runs and not on travis).

**On travis:**
[Some](https://travis-ci.org/joonty/vdebug/jobs/233428678) test failures seem to be rather specific. But [others](https://travis-ci.org/joonty/vdebug/jobs/233055679) seem like everything broke.

**For local test runs:**
1. I assumed that I had to run `bundler exec rake travis` (I found that in the travis.yml file).
2. That fails and tells me to run `bundle install --path vendor/bundle` first. That again fails because it can not build the native extension for json 1.8.3 (the identifiers `rb_cFixnum` and `rb_cBignum` are not declared in `generate_json()` in `generator.c`). I can install json 2.something just fine with gem so I decided to remove the Gemfile.lock. This way I can at least do the `bundle install`.
3. Now I get `Vimrunner::NoSuitableVimError` all over the place because my version of vim does not have `+xterm_clipboard`.  ~I have not yet found a way to install that on Arch Linux (besides manually compiling vim).~ gvim has the relevant features.
4. Next `bundler exec rake travis` fails because it can not find the X server. I now found that the travis file and the rakefile both set DISPLAY and therefore seem to so some setup work twice.
5. So at last when running `bundler exec rake test:all` some test pass and some cucumber tests fail with a message "Error, vdebug is not running".

**Questions/Suggestions:**
1. Can you run the tests locally?
1. Do you know why the tests on travis fail in random ways?
2. Can you `bundle install` locally? If not do you get the same error? Should we remove or update the lock file?
3. As there are python unit tests I assume that these are integration tests or something else. Can we move part of these tests to the python test suite (for example if there are unittests in there)?

### PR DESCRIPTION
**Pull request by lucc**
These are some small improvements and fixes for the test runs on travis.  See the individual commit messages for explanations.  Sadly this is independent from #284 so it does not fix #284.

### CODE REVIEW

**Comment by BlackIkeEagle** [comment]
Would it not be more interesting to remove the python 2.6 tests. Is there an important reason to keep 2.6 supported?

**Comment by lucc** [comment]
No I don't see any.

**Comment by BlackIkeEagle** [comment]
I'd rather drop the 2.6 test then, than to fiddle with things to make it work

**Comment by BlackIkeEagle** [comment]
especially since the goal is py3

**Comment by lucc** [comment]
updated.

**Comment by BlackIkeEagle** [comment]
thanks

**Pull request merged**
